# Generated by Django 2.2.3 on 2019-10-24 07:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20191019_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image1',
            field=models.ImageField(default=-1.0, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='image2',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
    ]
