# Generated by Django 2.2.3 on 2019-11-26 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='card_number',
            field=models.IntegerField(default=0),
        ),
    ]
